baseURL = 'https://timothyelems.github.io/'
languageCode = 'en-us'
title = 'Timothy Elems'
author = "timothyelems"
theme = "saral"

favicon = "static/favicon.ico"

[params]
    logoText = "Timothy Elems"
    isBlogFocused = true
    showHeroImage = true
    showResumeButton = true
    subtitle = 'Problem Solver... Mainly With Code'
    math = true

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['@@', '@@']]
          inline = [['@', '@']]
    
[menu]
  # [[menu.main]]
    # name = "Home"
    # pre = "home"
    # url = "/"
    # weight = 10
  [[menu.main]]
    name = "Writings"
    pre = "pen-tool"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    name = "Khalil Mack"
    pre = "pen-tool"
    url = "/khalil/"
    weight = 20
  # [[menu.main]]
    # name = "Projects"
    # pre = "projects"
    # url = "/projects/"
    # weight = 30
  # [[menu.main]]
    # name = "About"
    # pre = "about"
    # url = "/about/"
    # weight = 40
  [[menu.main]]
    name = "Contact"
    pre = "contact"
    url = "contact.md"
    weight = 30
  [[menu.main]]
   name = "Journey"
   pre = "journey"
   url = "https://timothyelems.github.io/resume/"
   weight = 40


  [module]
  [module.hugoVersion]
    extended = true
    min = "0.92.0"
    max = "0.123.8"
